name: NodeJS build App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn

    - name: Run lint code
      run: yarn run lint

    - name: Compile application to binary
      run: yarn run build

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: helm-assistant-linux-amd64
        path: helm-assistant

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: helm-assistant-linux-amd64
          path: helm-assistant

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Run test -> deploy_worker
        run: |
          ls -lah
          export HELM_ASSISTANT_BIN_CMD="./helm-assistant"
          export TESTS_PWD=$(pwd)/tests/
          bash tests/deploy_worker.sh
